### ISSUE TITLE
Expose Design and Architecture of the Tracking System via Console

### ISSUE THREAD

**Issue by arunqa** [opsfolio/resource-surveillance-commons#3]
Expose the design and architecture of the tracking system through the "Console" using "Provenance" pages in the Web UI. Ensure that SQLPage Web UIs display provenance information on every page that presents data, clearly identifying the source and handling process of the researcher’s data.

Tasks
- [ ] Integrate "Provenance" pages into the Web UI.
- [ ] Ensure that all SQLPage Web UIs display provenance information.
- [ ] Clearly identify and present data sources and handling processes on each relevant page.
